spring:
  datasource:
    url: jdbc:mysql://192.168.100.134:3306/batch?useSSL=false&serverTimezone=Asia/Seoul
    username: lmdb_user
    password: lmdb123!
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true # JPA 쿼리 로그 출력

  # 애플리케이션 이름 설정
  application:
    name: FileBatch

  sql:
    init:
      mode: never # SQL 스크립트 실행을 무조건 활성화

  batch:
    platform: mysql
    jdbc:
      initialize-schema: always
    job:
      enabled: false

file:
  input: D:\\download\\batch_test.txt