spring:
  datasource:
    url: jdbc:mysql://localhost:3306/batch?useSSL=false&serverTimezone=Asia/Seoul
    username: ENC(CP6FzQYT/Sv52TQi4/9U2Q==)
    password: ENC(36jn6vIZOaywDFHJOUEHGBwjf0ipBYv/)
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true # JPA 쿼리 로그 출력

  # 애플리케이션 이름 설정
  application:
    name: FileBatch

  sql:
    init:
      mode: never # SQL 스크립트 실행을 무조건 활성화

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

jasypt:
  encryptor:
    bean: jasyptEncryptor # Jasypt 빈 등록

file:
  input: D:\\download\\batch_test.txt