spring:
  datasource:
    url: jdbc:mariadb://192.168.100.134:3306/batch?useSSL=false&serverTimezone=Asia/Seoul
    username: ENC(mJ1p9qUWduBp2jYzSXNjfzu6OuXPOPBM)
    password: ENC(BvFDqKaeFKnB7fgaLQeyCSiI3q2kD+4P)
    driverClassName: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # JPA 엔티티가 있다면 'none'으로 설정하여 Spring Batch 스키마 초기화와 충돌 방지
    show-sql: true # JPA 쿼리 로그 출력

  # 애플리케이션 이름 설정
  application:
    name: FileBatch

  sql:
    init:
      mode: never # SQL 스크립트 실행을 무조건 활성화

  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false

jasypt:
  encryptor:
    bean: jasyptEncryptor # Jasypt 빈 등록

file:
  input: D:\\download\\batch_test.txt