spring:
  # H2 데이터베이스 설정 (인메모리 DB)
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  
  # H2 콘솔 접근 활성화 (개발 환경에서 DB 상태 확인용)
  h2:
    console:
      enabled: true
      path: /h2-console # http://localhost:8080/h2-console 로 접속 가능
  
  # 애플리케이션 이름 설정
  application:
    name: FileBatch
  
  sql:
    init:
      mode: always # SQL 스크립트 실행을 무조건 활성화
      platform: h2 # resources/schema-h2.sql 파일을 찾도록 명시
  
  batch:
    platform: h2
    jdbc:
      initialize-schema: never
    job:
      enabled: true
      names: importUserJob

file:
  input: D:\\download\\test.txt